services:
  crypto-api:
    build:
      context: ./crypto_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./crypto_api:/app

  crypto-frontend:
    build:
      context: ./crypto_frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - crypto-api
